function [sig_times, first, last] = CBPT_sig_timewindow(CBPT, alpha)
% Function to extract significant time window of CBPT output (generated by
% ft_freqstatistics)
% requires output with signficant clusters, averaged across freqs.
% returns:
% sig_times: significant time points as numbers
% first: first significant time point as s
% last: last significant time poitn as s
%
% Adriana Boettcher, 2022

% extract probability values
prob = squeeze(CBPT.prob);
% minimum value of all electrodes at every time point
prob_min = min(prob);
% significant time points
sig_times = find(prob_min < alpha);
% first sig time point
first = CBPT.time(min(sig_times));
% last sig time point
last = CBPT.time(max(sig_times));

end